
package com.energyvera.view;

import com.energyvera.model.inventario;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class FrmEditarInventario extends javax.swing.JFrame {

    private FrmInventario parentForm;
    private inventario inventarioEditar;

    public FrmEditarInventario(FrmInventario parent, inventario inventarioEditar) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        this.parentForm = parent;
        this.inventarioEditar = inventarioEditar;

        if (inventarioEditar != null) {
            cargarDatos();
        } else {
            Codigo_jTextField.setText("AUTO");
            Codigo_jTextField.setEditable(false);
        }
    }
private void cargarDatos() {
    Codigo_jTextField.setText(String.valueOf(inventarioEditar.getIdInventario()));
    Ubicacion_jTextField1.setText(inventarioEditar.getUbicacion());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Codigo_jTextField = new javax.swing.JTextField();
        Ubicacion_jTextField1 = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        jLabel2.setText("Código");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Editar inventario");

        jLabel3.setText("Código");

        jLabel4.setText("Ubicación");

        Codigo_jTextField.setText("error");

        Ubicacion_jTextField1.setText("error");
        Ubicacion_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ubicacion_jTextField1ActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Guardar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Codigo_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ubicacion_jTextField1)))))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Codigo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Ubicacion_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
                                           
    String ubicacion = Ubicacion_jTextField1.getText().trim();

    if (ubicacion.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "La ubicación no puede estar vacía",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Nuevo inventario
    if (inventarioEditar == null) {
        inventario nuevo = new inventario();
        nuevo.setUbicacion(ubicacion);

        parentForm.inventarioService.registrarInventario(nuevo);

        JOptionPane.showMessageDialog(this,
            "Inventario registrado correctamente",
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE);
    } 
    // Editando inventario existente
    else {
        inventarioEditar.setUbicacion(ubicacion);

        parentForm.inventarioService.actualizarInventario(inventarioEditar);

        JOptionPane.showMessageDialog(this,
            "Inventario actualizado",
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE);
    }

    parentForm.mostrarListaInventario();
    this.dispose();


    }//GEN-LAST:event_GuardarActionPerformed

    private void Ubicacion_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ubicacion_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ubicacion_jTextField1ActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
                                  
    int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Desea cancelar sin guardar los cambios?",
            "Cancelar edición",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (opcion == JOptionPane.YES_OPTION) {
        this.dispose();
    }


    }//GEN-LAST:event_CancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Codigo_jTextField;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField Ubicacion_jTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
