/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.energyvera.view;

import com.energyvera.model.vendedor;
import com.energyvera.service.vendedorService;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author PC-PERSONAL
 */
public class FrmEditarCrearVendedor extends javax.swing.JFrame {

    static private vendedor vendedorEditar;
    //Se puede enviar un modelo nulo para crearlo
    static private vendedorService serviceVendor;
    //Necesario para llamar de vuelta la vista de la tabla y para añadir el modelo actual
    /**
     * Creates new form FrmEditarCliente
     */
    public FrmEditarCrearVendedor(vendedor vendedorEditar, vendedorService serviceVendor) {
        this.vendedorEditar = vendedorEditar;
        this.serviceVendor = serviceVendor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_JLabel = new javax.swing.JLabel();
        Codigo_jTextField = new javax.swing.JTextField();
        Nombre_jTextField = new javax.swing.JTextField();
        Cargo_jTextField3 = new javax.swing.JTextField();
        Codigo_JLabel = new javax.swing.JLabel();
        Nombre_JLabel = new javax.swing.JLabel();
        Direccion_JLabel = new javax.swing.JLabel();
        Guardar_jButton = new javax.swing.JButton();
        Cancelar_jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo_JLabel.setText("Error: modo no establecido");

        Codigo_jTextField.setText("error");

        Nombre_jTextField.setText("error");

        Cargo_jTextField3.setText("error");

        Codigo_JLabel.setText("Código");

        Nombre_JLabel.setText("Nombre");

        Direccion_JLabel.setText("Cargo");

        Guardar_jButton.setText("error");
        Guardar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_jButtonActionPerformed(evt);
            }
        });

        Cancelar_jButton2.setText("Cancelar");
        Cancelar_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nombre_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Codigo_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Direccion_JLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Cancelar_jButton2)
                        .addGap(19, 19, 19)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Cargo_jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(Nombre_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Codigo_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Guardar_jButton)
                        .addGap(11, 11, 11)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo_JLabel)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Titulo_JLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codigo_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_JLabel)
                    .addComponent(Nombre_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cargo_jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion_JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar_jButton)
                    .addComponent(Cancelar_jButton2))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Guardar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_jButtonActionPerformed
        try {
                //Verificar que los campos no estén vacíos
            if (Codigo_jTextField.getText().isBlank()
                    || Nombre_jTextField.getText().isBlank()
                    || Cargo_jTextField3.getText().isBlank()
                    ) {
                throw new NullPointerException("");
            }
                //Intentar conversión
                int cod_factVenta = Integer.parseInt(Codigo_jTextField.getText());
                vendedorEditar.setIdVendedor(cod_factVenta);
                vendedorEditar.setNombre(Nombre_jTextField.getText());
                vendedorEditar.setCargo(Cargo_jTextField3.getText());
            } catch (NumberFormatException n) {//Código inútil pero bueh igual las excepciones no les hacen daño a nadie
                JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "Asegurese que los campos númericos no contengan espacios o puntos", 2);
                return;
            } catch (NullPointerException e){
                JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "Asegurese que los campos esten completos", 2);
                return;
            }
        //Detectar si estamos creando un nuevo cliente o editando uno actual para actualizarlo o guardarlo
        if (vendedorEditar != null) {
            serviceVendor.actualizarCargos(vendedorEditar); //Por que actualizar cargos?
            JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "factura " + vendedorEditar.getNombre()+ " editado exitosamente!", 2);
        } else {
            serviceVendor.registrarVendedor(vendedorEditar);
            JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "factura " + vendedorEditar.getNombre()+ " añadido exitosamente!", 2);
        }
        FrmVendedores factForm = new FrmVendedores(serviceVendor);
        factForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Guardar_jButtonActionPerformed

    private void Cancelar_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_jButton2ActionPerformed
        FrmVendedores factForm = new FrmVendedores(serviceVendor);
        factForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancelar_jButton2ActionPerformed
    
    
    public void inicializarVista() {
        if (vendedorEditar != null) {
            Titulo_JLabel.setText("Editar Factura");
            Codigo_jTextField.setText(String.valueOf(vendedorEditar.getIdVendedor()));
            Nombre_jTextField.setText(vendedorEditar.getNombre());
            Cargo_jTextField3.setText(String.valueOf(vendedorEditar.getCargo()));
            Guardar_jButton.setText("Guardar");
        }else{
            Titulo_JLabel.setText("Añadir Factura");
            Codigo_jTextField.setText("Número sin espacios ni letras");
            Nombre_jTextField.setText("");
            Cargo_jTextField3.setText("");
            Guardar_jButton.setText("Añadir");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditarCrearVendedor(vendedorEditar, serviceVendor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar_jButton2;
    private javax.swing.JTextField Cargo_jTextField3;
    private javax.swing.JLabel Codigo_JLabel;
    private javax.swing.JTextField Codigo_jTextField;
    private javax.swing.JLabel Direccion_JLabel;
    private javax.swing.JButton Guardar_jButton;
    private javax.swing.JLabel Nombre_JLabel;
    private javax.swing.JTextField Nombre_jTextField;
    private javax.swing.JLabel Titulo_JLabel;
    // End of variables declaration//GEN-END:variables
}
