/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.energyvera.view;

import com.energyvera.model.producto;
import com.energyvera.service.productoService;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author PC-PERSONAL
 */
public class FrmEditarCrearProducto extends javax.swing.JFrame {

    static private producto productoEditar;
    //Se puede enviar un modelo nulo para crearlo
    static private productoService serviceProd;
    //Necesario para llamar de vuelta la vista de la tabla y para añadir el modelo actual
    /**
     * Creates new form FrmEditarCliente
     */
    public FrmEditarCrearProducto(producto productoEditar, productoService servicioFactVenta) {
        this.productoEditar = productoEditar;
        this.serviceProd = servicioFactVenta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_JLabel = new javax.swing.JLabel();
        Codigo_jTextField = new javax.swing.JTextField();
        Marca_jTextField = new javax.swing.JTextField();
        Precio_jTextField3 = new javax.swing.JTextField();
        Stock_jTextField = new javax.swing.JTextField();
        Codigo_JLabel = new javax.swing.JLabel();
        Marca_JLabel = new javax.swing.JLabel();
        Precio_JLabel = new javax.swing.JLabel();
        Stock_JLabel = new javax.swing.JLabel();
        Guardar_jButton = new javax.swing.JButton();
        Cancelar_jButton2 = new javax.swing.JButton();
        CodVendorjLabel = new javax.swing.JLabel();
        Tipo_jTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo_JLabel.setText("Error: modo no establecido");

        Codigo_jTextField.setText("error");

        Marca_jTextField.setText("error");

        Precio_jTextField3.setText("error");

        Stock_jTextField.setText("error");
        Stock_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stock_jTextFieldActionPerformed(evt);
            }
        });

        Codigo_JLabel.setText("Código");

        Marca_JLabel.setText("Marca");

        Precio_JLabel.setText("Precio");

        Stock_JLabel.setText("Stock");

        Guardar_jButton.setText("error");
        Guardar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_jButtonActionPerformed(evt);
            }
        });

        Cancelar_jButton2.setText("Cancelar");
        Cancelar_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_jButton2ActionPerformed(evt);
            }
        });

        CodVendorjLabel.setText("Tipo");

        Tipo_jTextField.setText("error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Stock_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Marca_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Codigo_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancelar_jButton2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Precio_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodVendorjLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Stock_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(Precio_jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Marca_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Codigo_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar_jButton)
                    .addComponent(Tipo_jTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo_JLabel)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Titulo_JLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codigo_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marca_JLabel)
                    .addComponent(Marca_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio_JLabel)
                    .addComponent(Precio_jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stock_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stock_JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodVendorjLabel)
                    .addComponent(Tipo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar_jButton2)
                    .addComponent(Guardar_jButton))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Deprecated
    private void Stock_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stock_jTextFieldActionPerformed
        //Cliqué 2 veces, lo siento, aparte esto se repetirá en todos lados osea xd
    }//GEN-LAST:event_Stock_jTextFieldActionPerformed

    private void Guardar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_jButtonActionPerformed
        try {
                //Verificar que los campos no estén vacíos
            if (Codigo_jTextField.getText().isBlank()
                    || Marca_jTextField.getText().isBlank()
                    || Precio_jTextField3.getText().isBlank()
                    || Stock_jTextField.getText().isBlank()
                    || Tipo_jTextField.getText().isBlank()
                    ) {
                throw new NullPointerException("");
            }
                //Intentar conversión
                int cod_producto = Integer.parseInt(Codigo_jTextField.getText());
                productoEditar.setIdProducto(cod_producto);
                productoEditar.setMarca(Marca_jTextField.getText());
                int stock_prod = Integer.parseInt(Precio_jTextField3.getText());
                productoEditar.setPrecio(stock_prod);
                int stock = Integer.parseInt(Stock_jTextField.getText());
                productoEditar.setStock(stock);
                productoEditar.setTipo(Stock_jTextField.getText());
            } catch (NumberFormatException n) {
                JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "Asegurese que los campos númericos no contengan espacios o puntos", 2);
                return;
            } catch (NullPointerException e){
                JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "Asegurese que los campos esten completos", 2);
                return;
            }
        //Detectar si estamos creando un nuevo cliente o editando uno actual para actualizarlo o guardarlo
        if (productoEditar != null) {
            serviceProd.actualizarProducto(productoEditar);
            JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "factura " + productoEditar.getIdProducto()+ " editado exitosamente!", 2);
        } else {
            serviceProd.registrarProducto(productoEditar);
            JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "factura " + productoEditar.getIdProducto()+ " añadido exitosamente!", 2);
        }
        FrmProductos factForm = new FrmProductos(serviceProd);
        factForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Guardar_jButtonActionPerformed

    private void Cancelar_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_jButton2ActionPerformed
        FrmProductos factForm = new FrmProductos(serviceProd);
        factForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancelar_jButton2ActionPerformed
    
    
    public void inicializarVista() {
        if (productoEditar != null) {
            Titulo_JLabel.setText("Editar Producto");
            Codigo_jTextField.setText(String.valueOf(productoEditar.getIdProducto()));
            Marca_jTextField.setText(productoEditar.getMarca());
            Precio_jTextField3.setText(String.valueOf(productoEditar.getPrecio()));
            Stock_jTextField.setText(String.valueOf(productoEditar.getStock()));
            Tipo_jTextField.setText(String.valueOf(productoEditar.getTipo()));
            Guardar_jButton.setText("Guardar");
        }else{
            Titulo_JLabel.setText("Añadir Producto");
            Codigo_jTextField.setText("Número sin espacios ni letras");
            Marca_jTextField.setText("");
            Precio_jTextField3.setText("Número sin espacios ni letras");
            Stock_jTextField.setText("Número son espacios ni letras");
            Tipo_jTextField.setText("");
            Guardar_jButton.setText("Añadir");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditarCrearProducto(productoEditar, serviceProd).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar_jButton2;
    private javax.swing.JLabel CodVendorjLabel;
    private javax.swing.JLabel Codigo_JLabel;
    private javax.swing.JTextField Codigo_jTextField;
    private javax.swing.JButton Guardar_jButton;
    private javax.swing.JLabel Marca_JLabel;
    private javax.swing.JTextField Marca_jTextField;
    private javax.swing.JLabel Precio_JLabel;
    private javax.swing.JTextField Precio_jTextField3;
    private javax.swing.JLabel Stock_JLabel;
    private javax.swing.JTextField Stock_jTextField;
    private javax.swing.JTextField Tipo_jTextField;
    private javax.swing.JLabel Titulo_JLabel;
    // End of variables declaration//GEN-END:variables
}
