/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.energyvera.view;

import com.energyvera.model.facturaVenta;
import com.energyvera.service.facturaVentaService;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author PC-PERSONAL
 */
public class FrmEditarCrearFacturaVenta extends javax.swing.JFrame {

    static private facturaVenta facturaEditar;
    //Se puede enviar un modelo nulo para crearlo
    static private facturaVentaService serviceFactVenta;
    //Necesario para llamar de vuelta la vista de la tabla y para añadir el modelo actual
    /**
     * Creates new form FrmEditarCliente
     */
    public FrmEditarCrearFacturaVenta(facturaVenta facturaEditar, facturaVentaService servicioFactVenta) {
        this.facturaEditar = facturaEditar;
        this.serviceFactVenta = servicioFactVenta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_JLabel = new javax.swing.JLabel();
        Codigo_jTextField = new javax.swing.JTextField();
        Fecha_jTextField = new javax.swing.JTextField();
        IVA_jTextField3 = new javax.swing.JTextField();
        CodCliente_jTextField = new javax.swing.JTextField();
        Codigo_JLabel = new javax.swing.JLabel();
        Nombre_JLabel = new javax.swing.JLabel();
        Direccion_JLabel = new javax.swing.JLabel();
        Correo_JLabel = new javax.swing.JLabel();
        Guardar_jButton = new javax.swing.JButton();
        Cancelar_jButton2 = new javax.swing.JButton();
        CodVendorjLabel = new javax.swing.JLabel();
        CodVendor_jTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo_JLabel.setText("Error: modo no establecido");

        Codigo_jTextField.setText("error");

        Fecha_jTextField.setText("error");

        IVA_jTextField3.setText("error");

        CodCliente_jTextField.setText("error");
        CodCliente_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodCliente_jTextFieldActionPerformed(evt);
            }
        });

        Codigo_JLabel.setText("Código");

        Nombre_JLabel.setText("Fecha");

        Direccion_JLabel.setText("IVA:");

        Correo_JLabel.setText("Código Cliente");

        Guardar_jButton.setText("error");
        Guardar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_jButtonActionPerformed(evt);
            }
        });

        Cancelar_jButton2.setText("Cancelar");
        Cancelar_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_jButton2ActionPerformed(evt);
            }
        });

        CodVendorjLabel.setText("Código Vendedor");

        CodVendor_jTextField.setText("error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Correo_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Codigo_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancelar_jButton2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Direccion_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodVendorjLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CodCliente_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(IVA_jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Codigo_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar_jButton)
                    .addComponent(CodVendor_jTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo_JLabel)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Titulo_JLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codigo_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_JLabel)
                    .addComponent(Fecha_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion_JLabel)
                    .addComponent(IVA_jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodCliente_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo_JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodVendorjLabel)
                    .addComponent(CodVendor_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar_jButton2)
                    .addComponent(Guardar_jButton))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Deprecated
    private void CodCliente_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodCliente_jTextFieldActionPerformed
        //Cliqué 2 veces, lo siento, aparte esto se repetirá en todos lados osea xd
    }//GEN-LAST:event_CodCliente_jTextFieldActionPerformed

    private void Guardar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_jButtonActionPerformed
        try {
                //Verificar que los campos no estén vacíos
            if (Codigo_jTextField.getText().isBlank()
                    || Fecha_jTextField.getText().isBlank()
                    || IVA_jTextField3.getText().isBlank()
                    || CodCliente_jTextField.getText().isBlank()
                    || CodVendor_jTextField.getText().isBlank()
                    ) {
                throw new NullPointerException("");
            }
                //Intentar conversión
                int cod_factVenta = Integer.parseInt(Codigo_jTextField.getText());
                facturaEditar.setIdFacturaVenta(cod_factVenta);
                Date fechaFactura = Date.valueOf(Fecha_jTextField.getText());
                facturaEditar.setFechaFacturaV(fechaFactura);
                int iva_factVenta = Integer.parseInt(IVA_jTextField3.getText());
                facturaEditar.setIva(iva_factVenta);
                int cod_cliente = Integer.parseInt(CodCliente_jTextField.getText());
                facturaEditar.setIdCliente(cod_cliente);
                int cod_vendor = Integer.parseInt(CodVendor_jTextField.getText());
                facturaEditar.setIdVendedor(cod_vendor);
            } catch (NumberFormatException n) {
                JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "Asegurese que los campos númericos no contengan espacios o puntos", 2);
                return;
            } catch (NullPointerException e){
                JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "Asegurese que los campos esten completos", 2);
                return;
            }
        //Detectar si estamos creando un nuevo cliente o editando uno actual para actualizarlo o guardarlo
        if (facturaEditar != null) {
            serviceFactVenta.actualizarFacturaVenta(facturaEditar);
            JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "factura " + facturaEditar.getIdFacturaVenta()+ " editado exitosamente!", 2);
        } else {
            serviceFactVenta.registrarFacturaVenta(facturaEditar);
            JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "factura " + facturaEditar.getIdFacturaVenta()+ " añadido exitosamente!", 2);
        }
        FrmFacturaVenta factForm = new FrmFacturaVenta(serviceFactVenta);
        factForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Guardar_jButtonActionPerformed

    private void Cancelar_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_jButton2ActionPerformed
        FrmFacturaVenta factForm = new FrmFacturaVenta(serviceFactVenta);
        factForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancelar_jButton2ActionPerformed
    
    
    public void inicializarVista() {
        if (facturaEditar != null) {
            Titulo_JLabel.setText("Editar Factura");
            Codigo_jTextField.setText(String.valueOf(facturaEditar.getIdCliente()));
            Fecha_jTextField.setText(facturaEditar.getFechaFacturaV().toString());
            IVA_jTextField3.setText(String.valueOf(facturaEditar.getIva()));
            CodCliente_jTextField.setText(String.valueOf(facturaEditar.getIdCliente()));
            CodVendor_jTextField.setText(String.valueOf(facturaEditar.getIdVendedor()));
            Guardar_jButton.setText("Guardar");
        }else{
            Titulo_JLabel.setText("Añadir Factura");
            Codigo_jTextField.setText("Número sin espacios ni letras");
            Fecha_jTextField.setText("Día/Mes/Año");
            IVA_jTextField3.setText("");
            CodCliente_jTextField.setText("Número sin espacios ni letras");
            CodVendor_jTextField.setText("Número sin espacios ni letras");
            Guardar_jButton.setText("Añadir");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearFacturaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearFacturaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearFacturaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearFacturaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditarCrearFacturaVenta(facturaEditar, serviceFactVenta).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar_jButton2;
    private javax.swing.JTextField CodCliente_jTextField;
    private javax.swing.JTextField CodVendor_jTextField;
    private javax.swing.JLabel CodVendorjLabel;
    private javax.swing.JLabel Codigo_JLabel;
    private javax.swing.JTextField Codigo_jTextField;
    private javax.swing.JLabel Correo_JLabel;
    private javax.swing.JLabel Direccion_JLabel;
    private javax.swing.JTextField Fecha_jTextField;
    private javax.swing.JButton Guardar_jButton;
    private javax.swing.JTextField IVA_jTextField3;
    private javax.swing.JLabel Nombre_JLabel;
    private javax.swing.JLabel Titulo_JLabel;
    // End of variables declaration//GEN-END:variables
}
