/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.energyvera.view;

import com.energyvera.model.garantia;
import com.energyvera.service.garantiaService;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author PC-PERSONAL
 */
public class FrmEditarCrearGarantia extends javax.swing.JFrame {

    static private garantia garantiaEditar;
    //Se puede enviar un modelo nulo para crearlo
    static private garantiaService serviceGarantia;
    //Necesario para llamar de vuelta la vista de la tabla y para añadir el modelo actual
    /**
     * Creates new form FrmEditarCliente
     */
    public FrmEditarCrearGarantia(garantia garantiaEditar, garantiaService garService) {
        this.garantiaEditar = garantiaEditar;
        this.serviceGarantia = garService;
        initComponents();
        inicializarVista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_JLabel = new javax.swing.JLabel();
        Codigo_jTextField = new javax.swing.JTextField();
        Motivo_jTextField = new javax.swing.JTextField();
        Fecha_jTextField3 = new javax.swing.JTextField();
        FacturaVenta_jTextField = new javax.swing.JTextField();
        Codigo_JLabel = new javax.swing.JLabel();
        Nombre_JLabel = new javax.swing.JLabel();
        Direccion_JLabel = new javax.swing.JLabel();
        Correo_JLabel = new javax.swing.JLabel();
        Guardar_jButton = new javax.swing.JButton();
        Cancelar_jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo_JLabel.setText("Error: modo no establecido");

        Codigo_jTextField.setText("error");

        Motivo_jTextField.setText("error");

        Fecha_jTextField3.setText("error");

        FacturaVenta_jTextField.setText("error");
        FacturaVenta_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturaVenta_jTextFieldActionPerformed(evt);
            }
        });

        Codigo_JLabel.setText("Código");

        Nombre_JLabel.setText("Motivo");

        Direccion_JLabel.setText("Fecha");

        Correo_JLabel.setText("Código FacturaVenta");

        Guardar_jButton.setText("error");
        Guardar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_jButtonActionPerformed(evt);
            }
        });

        Cancelar_jButton2.setText("Cancelar");
        Cancelar_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(Cancelar_jButton2)
                .addGap(62, 62, 62)
                .addComponent(Guardar_jButton)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Titulo_JLabel)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Correo_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Codigo_JLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Direccion_JLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FacturaVenta_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fecha_jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Motivo_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Codigo_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Titulo_JLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codigo_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_JLabel)
                    .addComponent(Motivo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion_JLabel)
                    .addComponent(Fecha_jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FacturaVenta_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar_jButton)
                    .addComponent(Cancelar_jButton2))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Deprecated
    private void FacturaVenta_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturaVenta_jTextFieldActionPerformed
        //Cliqué 2 veces, lo siento, aparte esto se repetirá en todos lados osea xd
    }//GEN-LAST:event_FacturaVenta_jTextFieldActionPerformed

    private void Guardar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_jButtonActionPerformed
        try {
                //Verificar que los campos no estén vacíos
            if (Codigo_jTextField.getText().isBlank()
                    || Motivo_jTextField.getText().isBlank()
                    || Fecha_jTextField3.getText().isBlank()
                    || FacturaVenta_jTextField.getText().isBlank()
                    ) {
                throw new NullPointerException("");
            }
                //Intentar conversión
                int cod_garantia = Integer.parseInt(Codigo_jTextField.getText());
                garantiaEditar.setIdGarantia(cod_garantia);
                Date fechaGarantia = Date.valueOf(Fecha_jTextField3.getText());
                garantiaEditar.setFecha(fechaGarantia);
                garantiaEditar.setMotivo(Motivo_jTextField.getText());
                int cod_FactVenta = Integer.parseInt(FacturaVenta_jTextField.getText());
                garantiaEditar.setIdFacturaV(cod_FactVenta);
            } catch (NumberFormatException n) {
                JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "Asegurese que los campos númericos no contengan espacios o puntos", 2);
                return;
            } catch (NullPointerException e){
                JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "Asegurese que los campos esten completos", 2);
                return;
            }
        //Detectar si estamos creando un nuevo cliente o editando uno actual para actualizarlo o guardarlo
        if (garantiaEditar != null) {
            serviceGarantia.actualizarGarantia(garantiaEditar);
            JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "Garantía " + garantiaEditar.getIdGarantia()+ " editada exitosamente!", 2);
        } else {
            serviceGarantia.registrarGarantia(garantiaEditar);
            JOptionPane.showMessageDialog(this, "Gestión EnergyVera", "Garantía " + garantiaEditar.getIdGarantia()+ " añadida exitosamente!", 2);
        }
        FrmGarantias factForm = new FrmGarantias(serviceGarantia);
        factForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Guardar_jButtonActionPerformed

    private void Cancelar_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_jButton2ActionPerformed
        FrmGarantias factForm = new FrmGarantias(serviceGarantia);
        factForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancelar_jButton2ActionPerformed
    
    
    public void inicializarVista() {
        if (garantiaEditar != null) {
            Titulo_JLabel.setText("Editar Factura");
            Codigo_jTextField.setText(String.valueOf(garantiaEditar.getIdGarantia()));
            Motivo_jTextField.setText(garantiaEditar.getMotivo());
            Fecha_jTextField3.setText(String.valueOf(garantiaEditar.getFecha()));
            FacturaVenta_jTextField.setText(String.valueOf(garantiaEditar.getIdFacturaV()));
            Guardar_jButton.setText("Guardar");
        }else{
            Titulo_JLabel.setText("Añadir Factura");
            Codigo_jTextField.setText("Número sin espacios ni letras");
            Motivo_jTextField.setText("");
            Fecha_jTextField3.setText("Día/Mes/Año");
            FacturaVenta_jTextField.setText("Número sin espacios ni letras");
            Guardar_jButton.setText("Añadir");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearGarantia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearGarantia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearGarantia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarCrearGarantia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditarCrearGarantia(garantiaEditar, serviceGarantia).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar_jButton2;
    private javax.swing.JLabel Codigo_JLabel;
    private javax.swing.JTextField Codigo_jTextField;
    private javax.swing.JLabel Correo_JLabel;
    private javax.swing.JLabel Direccion_JLabel;
    private javax.swing.JTextField FacturaVenta_jTextField;
    private javax.swing.JTextField Fecha_jTextField3;
    private javax.swing.JButton Guardar_jButton;
    private javax.swing.JTextField Motivo_jTextField;
    private javax.swing.JLabel Nombre_JLabel;
    private javax.swing.JLabel Titulo_JLabel;
    // End of variables declaration//GEN-END:variables
}
