package com.energyvera.view;

import com.energyvera.dao.VendedorDAO;
import com.energyvera.daoImpl.VendedorDAOImpl;
import com.energyvera.model.Cliente;
import com.energyvera.model.vendedor;
import javax.swing.JOptionPane;

/**
 *
 * @author PC-PERSONAL
 */
public class FrmEditarCliente extends javax.swing.JFrame {

    private FrmClientes parentForm;

    static private Cliente clienteEditar;
    private vendedor vendedorEditar;

    /**
     * Creates new form FrmEditarCliente
     */
    public FrmEditarCliente(FrmClientes parent, Cliente clienteEditar) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        this.parentForm = parent;
        this.clienteEditar = clienteEditar;

        if (clienteEditar != null) {
            obtenerDatos();  // ← carga los datos en los campos
        } else {
            Codigo_jTextField.setEditable(false);
            Codigo_jTextField.setText("AUTO");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Codigo_jTextField = new javax.swing.JTextField();
        Nombre_jTextField = new javax.swing.JTextField();
        Direccion_jTextField3 = new javax.swing.JTextField();
        Email_jTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Guardar_jButton = new javax.swing.JButton();
        Cancelar_jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Editar Cliente");

        Codigo_jTextField.setText("error");

        Nombre_jTextField.setText("error");

        Direccion_jTextField3.setText("error");

        Email_jTextField.setText("error");
        Email_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_jTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Código");

        jLabel3.setText("Nombre");

        jLabel4.setText("Dirección");

        jLabel5.setText("Correo");

        Guardar_jButton.setText("Guardar");
        Guardar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_jButtonActionPerformed(evt);
            }
        });

        Cancelar_jButton2.setText("Cancelar");
        Cancelar_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cancelar_jButton2)
                                .addGap(68, 68, 68)
                                .addComponent(Guardar_jButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email_jTextField)
                                    .addComponent(Direccion_jTextField3)
                                    .addComponent(Nombre_jTextField)
                                    .addComponent(Codigo_jTextField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nombre_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Direccion_jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar_jButton)
                    .addComponent(Cancelar_jButton2))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Email_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_jTextFieldActionPerformed

    private void Guardar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_jButtonActionPerformed
        try {
            // Si clienteEditar es null → es un cliente nuevo
            if (clienteEditar == null) {
                Cliente nuevo = new Cliente();
                nuevo.setNombre(Nombre_jTextField.getText());
                nuevo.setDireccion(Direccion_jTextField3.getText());
                nuevo.setEmail(Email_jTextField.getText());

                // Llamar a tu DAO
                com.energyvera.daoImpl.ClienteDAOImpl dao = new com.energyvera.daoImpl.ClienteDAOImpl();
                dao.insertar(nuevo);

                JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente.");
            } else {
                // Editar cliente existente
                clienteEditar.setNombre(Nombre_jTextField.getText());
                clienteEditar.setDireccion(Direccion_jTextField3.getText());
                clienteEditar.setEmail(Email_jTextField.getText());

                // Llamar al DAO para actualizar
                com.energyvera.daoImpl.ClienteDAOImpl dao = new com.energyvera.daoImpl.ClienteDAOImpl();
                dao.actualizar(clienteEditar);

                JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente.");
            }

            // Cerrar la ventana
            parentForm.mostrarListaClientes();
            this.dispose();



        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: verifique los datos ingresados",
                    "Gestión EnergyVera",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_Guardar_jButtonActionPerformed

    private void Cancelar_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_jButton2ActionPerformed
        parentForm.mostrarListaClientes();
        this.dispose();

    }//GEN-LAST:event_Cancelar_jButton2ActionPerformed

    public void obtenerDatos() {
        Codigo_jTextField.setText(String.valueOf(clienteEditar.getIdCliente()));
        Nombre_jTextField.setText(clienteEditar.getNombre());
        Direccion_jTextField3.setText(clienteEditar.getDireccion());
        Email_jTextField.setText(clienteEditar.getEmail());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar_jButton2;
    private javax.swing.JTextField Codigo_jTextField;
    private javax.swing.JTextField Direccion_jTextField3;
    private javax.swing.JTextField Email_jTextField;
    private javax.swing.JButton Guardar_jButton;
    private javax.swing.JTextField Nombre_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
