/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.energyvera.view;

/**
 *
 * @author PC-PERSONAL
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Energyvera_jLabel = new javax.swing.JLabel();
        MenuPrincipal_jLabel = new javax.swing.JLabel();
        Facturas_JButton = new javax.swing.JButton();
        Clientes_JButton = new javax.swing.JButton();
        Inventario_JButton = new javax.swing.JButton();
        Garantias_JButton = new javax.swing.JButton();
        Vendedores_JButton = new javax.swing.JButton();
        Proveedores_JButton = new javax.swing.JButton();
        Productos_JButton = new javax.swing.JButton();
        SeleccionaOpcion_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Energyvera_jLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Energyvera_jLabel.setText("Gestión EnergyVera");

        MenuPrincipal_jLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuPrincipal_jLabel.setText("Menú Principal");

        Facturas_JButton.setText("Facturas");
        Facturas_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Facturas_JButtonActionPerformed(evt);
            }
        });

        Clientes_JButton.setText("Clientes");
        Clientes_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clientes_JButtonActionPerformed(evt);
            }
        });

        Inventario_JButton.setText("Inventario");
        Inventario_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inventario_JButtonActionPerformed(evt);
            }
        });

        Garantias_JButton.setText("Garantías");
        Garantias_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Garantias_JButtonActionPerformed(evt);
            }
        });

        Vendedores_JButton.setText("Vendedores");
        Vendedores_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendedores_JButtonActionPerformed(evt);
            }
        });

        Proveedores_JButton.setText("Proveedores");
        Proveedores_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proveedores_JButtonActionPerformed(evt);
            }
        });

        Productos_JButton.setText("Productos");
        Productos_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos_JButtonActionPerformed(evt);
            }
        });

        SeleccionaOpcion_jLabel.setText("Seleccione una opción a administrar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeleccionaOpcion_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Clientes_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Facturas_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Inventario_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Vendedores_JButton))
                            .addGap(13, 13, 13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Proveedores_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Garantias_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Productos_JButton)
                        .addGap(62, 62, 62)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Energyvera_jLabel)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(MenuPrincipal_jLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Energyvera_jLabel)
                .addGap(18, 18, 18)
                .addComponent(MenuPrincipal_jLabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(SeleccionaOpcion_jLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Facturas_JButton)
                            .addComponent(Clientes_JButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Inventario_JButton)
                            .addComponent(Garantias_JButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vendedores_JButton)
                            .addComponent(Proveedores_JButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Productos_JButton)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Nada de conectar botones, directamente se relaciona su acción con código
    /*Todos los métodos de JButtonActionPerfomed abren una nueva clase 
    del tipo requerido en el paquete y desecha la ventana de menú principal.
    */
    private void Productos_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos_JButtonActionPerformed
        FrmProductos ventanaPr = new FrmProductos();
        ventanaPr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Productos_JButtonActionPerformed

    private void Clientes_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clientes_JButtonActionPerformed
        FrmClientes ventanaCl = new FrmClientes();
        ventanaCl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Clientes_JButtonActionPerformed

    private void Facturas_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Facturas_JButtonActionPerformed
        FrmFacturaVenta ventanaF = new FrmFacturaVenta();
        ventanaF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Facturas_JButtonActionPerformed

    private void Inventario_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inventario_JButtonActionPerformed
        FrmInventario ventanaInv = new FrmInventario();
        ventanaInv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Inventario_JButtonActionPerformed

    private void Garantias_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Garantias_JButtonActionPerformed
        FrmGarantias ventanaGa = new FrmGarantias();
        ventanaGa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Garantias_JButtonActionPerformed

    private void Vendedores_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendedores_JButtonActionPerformed
        FrmVendedores ventanaVe = new FrmVendedores();
        ventanaVe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Vendedores_JButtonActionPerformed

    private void Proveedores_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proveedores_JButtonActionPerformed
        FrmProveedores ventanaProv = new FrmProveedores();
        ventanaProv.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_Proveedores_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clientes_JButton;
    private javax.swing.JLabel Energyvera_jLabel;
    private javax.swing.JButton Facturas_JButton;
    private javax.swing.JButton Garantias_JButton;
    private javax.swing.JButton Inventario_JButton;
    private javax.swing.JLabel MenuPrincipal_jLabel;
    private javax.swing.JButton Productos_JButton;
    private javax.swing.JButton Proveedores_JButton;
    private javax.swing.JLabel SeleccionaOpcion_jLabel;
    private javax.swing.JButton Vendedores_JButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
